[package]
name = "page_108_extracting_data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
futures = "0.3.18"
serde = "1.0.130"
serde_json = "1.0.72"
