name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd new_project && cargo build --verbose
    - name: Run tests
      run: cd new_project && cargo test --verbose
    - name: Build
      run: cd projects/page_005_using_strings_in_rust && cargo build --verbose
    - name: Run tests
      run: cd projects/page_005_using_strings_in_rust && cargo test --verbose
    - name: Build
      run: cd projects/page_006_using_string_literals_in_rust && cargo build --verbose
    - name: Run tests
      run: cd projects/page_006_using_string_literals_in_rust && cargo test --verbose
    - name: Build
      run: cd projects/page_007_understanding_integers_and_floats && cargo build --verbose
    - name: Run tests
      run: cd projects/page_007_understanding_integers_and_floats && cargo test --verbose
    - name: Build
      run: cd projects/page_008_storing_data_in_vectors_and_arrays && cargo build --verbose
    - name: Run tests
      run: cd projects/page_008_storing_data_in_vectors_and_arrays && cargo test --verbose
    - name: Build
      run: cd projects/page_009_mapping_data_with_hash_maps && cargo build --verbose
    - name: Run tests
      run: cd projects/page_009_mapping_data_with_hash_maps && cargo test --verbose
    - name: Build
      run: cd projects/page_011_handling_results_and_errors && cargo build --verbose
    - name: Run tests
      run: cd projects/page_011_handling_results_and_errors && cargo test --verbose
    - name: Build
      run: cd projects/page_015_scopes && cargo build --verbose
    - name: Run tests
      run: cd projects/page_015_scopes && cargo test --verbose
